### ISSUE TITLE
File "/usr/local/bin/interlace", line 33, in <module>

### ISSUE THREAD

**Issue by xenion0** [pry0cc/axiom#612]
when i try to run axiom-scan in my kali machine give me error  
also i try to  install interlace from here https://github.com/codingo/Interlace 
with `python3 setup.py install`
```
┌──(root㉿kali)-[/home/kali/Documents/recon/]
└─# axiom-scan ips.txt -m masscan -p80,443 -o masscan.txt 
              _
  ____ __  __(_)___  ____ ___        ______________ _____                                                           
 / __ `/ |/_/ / __ \/ __ `__ \______/ ___/ ___/ __ `/ __ \                                                          
/ /_/ />  </ / /_/ / / / / / /_____(__  ) /__/ /_/ / / / /                                                          
\__,_/_/|_/_/\____/_/ /_/ /_/     /____/\___/\__,_/_/ /_/                                                           
                                                                                                                    
                                    @pry0cc                                                                         
                                 & @0xtavian                                                                        
                                                                                                                    
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.6', 'console_scripts', 'interlace')())
  File "/usr/local/bin/interlace", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/Interlace/interlace.py", line 6, in <module>
    from Interlace.lib.core.output import OutputHelper, Level
  File "/usr/local/lib/python3.10/dist-packages/Interlace/lib/core/output.py", line 4, in <module>
    from colorclass import Color
  File "/usr/local/lib/python3.10/dist-packages/colorclass/__init__.py", line 11, in <module>
    from colorclass.codes import list_tags  # noqa
  File "/usr/local/lib/python3.10/dist-packages/colorclass/codes.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.6', 'console_scripts', 'interlace')())
  File "/usr/local/bin/interlace", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/Interlace/interlace.py", line 6, in <module>
    from Interlace.lib.core.output import OutputHelper, Level
  File "/usr/local/lib/python3.10/dist-packages/Interlace/lib/core/output.py", line 4, in <module>
    from colorclass import Color
  File "/usr/local/lib/python3.10/dist-packages/colorclass/__init__.py", line 11, in <module>
    from colorclass.codes import list_tags  # noqa
  File "/usr/local/lib/python3.10/dist-packages/colorclass/codes.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
cat: /root/.axiom/tmp/masscan+166302548024228/hosts_preflight: No such file or directory
cp: cannot stat '/root/.axiom/tmp/masscan+166302548024228/hosts_preflight': No such file or directory
```

**Comment by 0xtavian** [comment]
@xenion0 Thats odd, I am able to get it working with python3.10. Can you first delete Interlace, run the following and try again?
```
git clone https://github.com/codingo/Interlace.git
cd Interlace
pip3 install -r requirements.txt
python3 setup.py install
```

They should have fixed this issue recently. If none of these work, you can try workarounds mentioned in their recently closed issues https://github.com/codingo/Interlace/issues?q=is%3Aissue+is%3Aclosed
